In [4]:
import pandas as pd
import os

folder_path = "raw_data"

all_files = [f for f in os.listdir(folder_path) if f.endswith(".txt")]

print(all_files)

['2020_eei_loads.txt', '2022_eei_loads.txt', '2025_eei_loads.txt', '2021_eei_loads.txt', '2024_eei_loads.txt', '2023_eei_loads.txt', '2018_eei_loads.txt', '2019_eei_loads.txt']

In [6]:
df_list = []

for file in all_files:
    file_path = os.path.join(folder_path, file)

    df = pd.read_csv(
        file_path,
        sep="\t",     # EEI format usually tab-separated
        engine="python"
    )

    df_list.append(df)

load_df = pd.concat(df_list, ignore_index=True)

load_df.head()

,010120201 116561121610915107881088811228117051204512374126551294713189,010120221 109831051010161 9970 997310144105121095611521122441290113300,010120251 114021100310665104631049010715110891144711907123551273713090,010120211 121921174011476113991150811856123541275812949129381295513171,010120241 119081152911244110861115211473118961227312596128021291912964,010120231 1051110050 9718 9532 9507 9687100991044710717108101092011103,010120181 157601529715014148951496515274157391616016760173101767817799,010120191 116281110310705104631041310636109911125711687122241252212523
0,010120202 13405134861360113972150521...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,010220201 11417110971099411082114831...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,010220202 14202141301429314717156921...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,010320201 11271108551065810636109481...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,010320202 14676146721459714664153171...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
load_df.columns
load_df.head()

,010120201 116561121610915107881088811228117051204512374126551294713189,010120221 109831051010161 9970 997310144105121095611521122441290113300,010120251 114021100310665104631049010715110891144711907123551273713090,010120211 121921174011476113991150811856123541275812949129381295513171,010120241 119081152911244110861115211473118961227312596128021291912964,010120231 1051110050 9718 9532 9507 9687100991044710717108101092011103,010120181 157601529715014148951496515274157391616016760173101767817799,010120191 116281110310705104631041310636109911125711687122241252212523
0,010120202 13405134861360113972150521...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,010220201 11417110971099411082114831...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,010220202 14202141301429314717156921...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,010320201 11271108551065810636109481...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,010320202 14676146721459714664153171...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
import pandas as pd

file_path = "raw_data/2018_eei_loads.txt"

with open(file_path, 'r') as f:
    lines = f.readlines()

records = []

for line in lines:
    line = line.strip()

    # Extract date (first 8 digits)
    date_str = line[:8]

    # Extract hour (9th digit)
    hour = int(line[8])

    # Remaining string contains load values
    load_values_str = line[9:]

    # Split into 5-digit chunks
    loads = [int(x) for x in load_values_str.split() if x.strip()]

    records.append([date_str, hour] + loads)

load_df = pd.DataFrame(records)

load_df.head()

,0,1,2,3,4,5,6,7,8
0,01012018,1,1576015297150141489514965152741573916160167601...,NaN,NaN,NaN,NaN,NaN,NaN
1,01012018,2,1776217644176171792919119202712011719710190571...,NaN,NaN,NaN,NaN,NaN,NaN
2,01022018,1,1522514902147811482415191161961795919013192121...,NaN,NaN,NaN,NaN,NaN,NaN
3,01022018,2,1856918507185871868419571206282061620230195591...,NaN,NaN,NaN,NaN,NaN,NaN
4,01032018,1,1503014631144701449714853158611761918609186071...,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
import pandas as pd
import re

records = []

for line in lines:
    date_str = line[:8]       # first 8 chars = date
    hour = int(line[8])       # 9th char = hour
    load_values_str = line[9:]  # rest of line

    # Extract all 5-digit numbers using regex
    loads = [int(x) for x in re.findall(r'\d{5}', load_values_str)]

    records.append([date_str, hour] + loads)

# Convert to DataFrame
load_df = pd.DataFrame(records)
print(load_df.head())

         0   1      2      3      4      5      6        7        8        9   \
0  01012018   1  15760  15297  15014  14895  14965  15274.0  15739.0  16160.0
1  01012018   2  17762  17644  17617  17929  19119  20271.0  20117.0  19710.0
2  01022018   1  15225  14902  14781  14824  15191  16196.0  17959.0  19013.0
3  01022018   2  18569  18507  18587  18684  19571  20628.0  20616.0  20230.0
4  01032018   1  15030  14631  14470  14497  14853  15861.0  17619.0  18609.0

        10       11       12       13
0  16760.0  17310.0  17678.0  17799.0
1  19057.0  18099.0  16854.0  15860.0
2  19212.0  19158.0  19017.0  18794.0
3  19559.0  18445.0  17012.0  15792.0
4  18607.0  18264.0  17896.0  17550.0

In [15]:
load_df.shape

(730, 14)

In [17]:
load_df = load_df.fillna(0)

In [19]:
print(load_df.head())

         0   1      2      3      4      5      6        7        8        9   \
0  01012018   1  15760  15297  15014  14895  14965  15274.0  15739.0  16160.0
1  01012018   2  17762  17644  17617  17929  19119  20271.0  20117.0  19710.0
2  01022018   1  15225  14902  14781  14824  15191  16196.0  17959.0  19013.0
3  01022018   2  18569  18507  18587  18684  19571  20628.0  20616.0  20230.0
4  01032018   1  15030  14631  14470  14497  14853  15861.0  17619.0  18609.0

        10       11       12       13
0  16760.0  17310.0  17678.0  17799.0
1  19057.0  18099.0  16854.0  15860.0
2  19212.0  19158.0  19017.0  18794.0
3  19559.0  18445.0  17012.0  15792.0
4  18607.0  18264.0  17896.0  17550.0

In [21]:
load_df = pd.DataFrame(records)

In [23]:
import pandas as pd
import re
import glob
import os

# ----------------------------
# CONFIG: folder containing load files
# ----------------------------
data_folder = "raw_data"

# ----------------------------

all_records = []
max_load_count = 0  # track max number of loads in any row

# ----------------------------
# STEP 1: Read all txt files
# ----------------------------
for file_path in glob.glob(os.path.join(data_folder, "*.txt")):
    with open(file_path, 'r') as f:
        lines = f.readlines()

    for line in lines:
        # Extract date and hour
        date_str = line[:8]  # first 8 chars
        hour_str = line[8]   # 9th char
        load_values_str = line[9:]  # rest of line

        # Extract all 5-digit numbers from the load string
        loads = [int(x) for x in re.findall(r'\d{5}', load_values_str)]

        # Track max load count for padding later
        if len(loads) > max_load_count:
            max_load_count = len(loads)

        # Append row: [date, hour, loads...]
        all_records.append([date_str, hour_str] + loads)

# ----------------------------
# STEP 2: Pad rows so all have same number of load columns
# ----------------------------
for i in range(len(all_records)):
    row_len = len(all_records[i])
    if row_len < 2 + max_load_count:  # 2 for date & hour
        all_records[i] += [0] * (2 + max_load_count - row_len)

# ----------------------------
# STEP 3: Create DataFrame
# ----------------------------
columns = ['date', 'hour'] + [f'load_{i+1}' for i in range(max_load_count)]
combined_df = pd.DataFrame(all_records, columns=columns)

# ----------------------------
# STEP 4: Clean date and convert to datetime
# ----------------------------
# Keep only the first 8 digits and extract numeric characters
combined_df['date'] = combined_df['date'].astype(str).str[:8].str.extract(r'(\d{8})')[0]

# Convert to datetime (errors='coerce' will mark unparseable dates as NaT)
combined_df['date'] = pd.to_datetime(combined_df['date'], format='%m%d%Y', errors='coerce')

# ----------------------------
# STEP 5: Convert hour to int and create hourly datetime
# ----------------------------
combined_df['hour'] = combined_df['hour'].astype(int)
combined_df['datetime'] = combined_df['date'] + pd.to_timedelta(combined_df['hour'] - 1, unit='h')

# Optional: drop original date and hour columns
combined_df = combined_df.drop(['date', 'hour'], axis=1)

# ----------------------------
# STEP 6: Fill any remaining NaNs (should be none after padding)
# ----------------------------
combined_df = combined_df.fillna(0)

# ----------------------------
# DONE
# ----------------------------
print("Preprocessing complete!")
print("Combined DataFrame shape:", combined_df.shape)
print(combined_df.head())

Preprocessing complete!
Combined DataFrame shape: (5844, 13)
   load_1  load_2  load_3  load_4  load_5  load_6  load_7  load_8  load_9  \
0   11656   11216   10915   10788   10888   11228   11705   12045   12374
1   13405   13486   13601   13972   15052   16012   15825   15384   14779
2   11417   11097   10994   11082   11483   12497   14147   15120   15218
3   14202   14130   14293   14717   15692   16559   16401   15925   15270
4   11271   10855   10658   10636   10948   11853   13349   14332   14622

   load_10  load_11  load_12            datetime
0    12655    12947    13189 2020-01-01 00:00:00
1    13947    12902    11994 2020-01-01 01:00:00
2    15073    14905    14578 2020-01-02 00:00:00
3    14292    13067    11987 2020-01-02 01:00:00
4    14769    14888    14801 2020-01-03 00:00:00

In [25]:
combined_df['datetime'].dt.year.value_counts()

datetime
2020    732
2024    732
2025    730
2022    730
2021    730
2023    730
2018    730
2019    730
Name: count, dtype: int64

In [27]:
print("Start:", combined_df['datetime'].min())
print("End:", combined_df['datetime'].max())

Start: 2018-01-01 00:00:00
End: 2025-12-31 01:00:00

In [29]:
# Go back to combined_df BEFORE melting
# Recreate base date properly

combined_df['base_date'] = combined_df['datetime'].dt.floor('D')

# Melt
load_long = combined_df.melt(
    id_vars=['base_date'],
    value_vars=[col for col in combined_df.columns if col.startswith('load_')],
    var_name='hour_block',
    value_name='load'
)

# Extract hour inside block (0–11)
load_long['hour_in_block'] = load_long['hour_block'].str.extract(r'(\d+)').astype(int) - 1

# Now detect whether row belonged to first or second block
# We determine this using repeating pattern (every 12 loads alternate)

# Reconstruct block index (0 or 1 per day)
load_long['block_index'] = load_long.groupby('base_date').cumcount() // 12

# Final hour = hour_in_block + (block_index * 12)
load_long['final_hour'] = load_long['hour_in_block'] + (load_long['block_index'] * 12)

# Create final datetime
load_long['datetime'] = load_long['base_date'] + pd.to_timedelta(load_long['final_hour'], unit='h')

# Clean
load_long = load_long[['datetime', 'load']].sort_values('datetime').reset_index(drop=True)

print(load_long.shape)
print("Start:", load_long['datetime'].min())
print("End:", load_long['datetime'].max())

(70128, 2)
Start: 2018-01-01 00:00:00
End: 2025-12-31 23:00:00

In [31]:
load_long.shape
load_long['datetime'].min()
load_long['datetime'].max()

Timestamp('2025-12-31 23:00:00')

In [35]:
save_path = "raw_data/iso_ne_load_2018_2025.csv"

load_long.to_csv(save_path, index=False)

print("Saved successfully!")

Saved successfully!

In [33]:
import os

# Extract the directory path from save_path
save_dir = os.path.dirname(save_path)

# Create the directory if it doesn't exist
os.makedirs(save_dir, exist_ok=True)

print(f"Created directory: {save_dir}")

Created directory: content/drive/MyDrive/Electricity_Load_Forecasting_ISONE/data/raw

**Reasoning**:
The directory has been created in the previous step, so now the `load_long` DataFrame can be saved to the specified path without encountering an `OSError`.

In [36]:
save_path = "raw_data/iso_ne_load_2018_2025.csv"

load_long.to_csv(save_path, index=False)

print("Saved successfully!")

Saved successfully!

In [37]:
load_long.describe()

                  datetime          load
count                70128  70128.000000
mean   2021-12-31 23:30:00  14717.378137
min    2018-01-01 00:00:00      0.000000
25%    2020-01-01 14:45:00  11717.000000
50%    2021-12-31 23:30:00  13635.000000
75%    2024-01-01 08:15:00  15694.000000
max    2025-12-31 23:00:00  99991.000000
std                    NaN  11950.900793